spring:
  profiles:
    active:
      - dev
      
---
server:
  port: 7001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-server

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false    #不注册自己 http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false          #自己端是注册中心，我的职责就是维护服务实例，不需要检索服务实例
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/

      
---
server:
  port: 7001
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-eureka-server

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false    #不注册自己 http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false          #自己端是注册中心，我的职责就是维护服务实例，不需要检索服务实例
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
